### PR TITLE
Add scippwidgets exercise

### PR DESCRIPTION
**Pull request by SimonHeybrock**

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
@OwenArnold This requires and extra module (`scippwidgets`) How should we handle installing this? Just add it to the gobal `yml`? Per-folder `yml`?

**Comment by OwenArnold** [comment]
> @OwenArnold This requires an extra module (`scippwidgets`) How should we handle installing this? Just add it to the gobal `yml`? Per-folder `yml`?

For now I would say the global `yml` but we might be heading in the direction of a per-folder yaml as some future refactor.

**Comment by SimonHeybrock** [comment]
@OwenArnold Any idea where this (unrelated?) build fail is coming form: https://dev.azure.com/scipp/ess-notebooks/_build/results?buildId=3172&view=logs&j=02884920-dea5-5903-1939-45a30e91825b&t=f6357ae2-7e8a-5f38-9945-358c351daa87&l=4207?

**Comment by OwenArnold** [comment]
> @OwenArnold Any idea where this (unrelated?) build fail is coming form: https://dev.azure.com/scipp/ess-notebooks/_build/results?buildId=3172&view=logs&j=02884920-dea5-5903-1939-45a30e91825b&t=f6357ae2-7e8a-5f38-9945-358c351daa87&l=4207?

I think that might have broken due to changes made upstream this morning. The old notebook is deprecated anyway, so this should fix your problems https://github.com/scipp/ess-notebooks/pull/28

**Comment by SimonHeybrock** [comment]
I'll merge this so it does not hold up other things, please review nonetheless.

**Pull request merged**
