### PR TITLE
Small corrections to the Amor notebooks

### PR DESCRIPTION
**Pull request by arm61**
Some changes to the Amor notebook based on feedback from Amor Instrument scientist.

### CODE REVIEW

**Comment by arm61** [comment]
failing cause of something `wfm` related @nvaytet ?

**Comment by nvaytet** [comment]
> failing cause of something `wfm` related @nvaytet ?

Yes, see https://github.com/scipp/ess-notebooks/pull/41
It's passing the builds but i currently have an issue with the long output from Mantid fitting showing up in the docs...

**Comment by arm61** [comment]
Sorry for the delay on this, was on my holidogs 🌴🐕.

**Comment by arm61** [comment]
@nvaytet Something with `scn.instrument_view`? I might have broke something...

**Comment by nvaytet** [comment]
Merged now, if you merge the latest changes from `main`, should be good to go

**Comment by arm61** [comment]
🎉🎉🎉

**Review by nvaytet — APPROVED** [review]

**Pull request merged**
